defaults:
  - _self_
  - /model/force_output@force_output: gradient                        # force-producing strategy
  - /model/output_modules@global_rescale_shift: global_rescale_shift  # normalize outputs
