defaults:
  - representation: painn
_convert_: all
_target_: curator.model.NeuralNetworkPotential

representation:
  readout:
    _target_: curator.layer.AtomwiseNN
    in_features: ${..num_features}
    out_features: 2
    output_keys:
    - key: energy
      per_atom: False
      aggregation_mode: sum
    - key: atomic_charge
      per_atom: false
      aggregation_mode: null
input_modules:
  - _target_: curator.layer.PairwiseDistance
    compute_neighbor_list: False
    compute_distance_from_R: True
output_modules:
  - _target_: curator.layer.GradientOutput
    grad_on_positions: True
    grad_on_edge_diff: False
  - _target_: curator.layer.ChargeEquilibration
    num_features: ${...representation.num_features}
  - _target_: curator.layer.GlobalScaleShift