simulator:
  engine:
    _target_: curator.simulate.engines.ase_md.MDEngine
    dynamics_cls: ase.md.langevin.Langevin
    timestep: 0.5
    friction: 0.2
    temperature_K: 300
  callbacks:
  - _target_: curator.simulate.callbacks.calc.CalculatorAssign
    calculator: ${model_path}
    warmup: true
    require_forces: false
    apply_to_neb_images: false
    device: ${device}
  - _target_: curator.simulate.callbacks.thermo_uncertainty.ThermoWithUncertainty
    interval: 1
    variables: basic_energies
    monitor: force_sd
    low: 0.05
    high: 0.5
    save_path: ./runs/ensemble_uncertainty/warning_struct.traj
    uncertain_count: null
    uncertainty_backend:
      _target_: curator.simulate.uncertainty.auto.AutoUncertainty
      calculator: ${calculator}
      dataset: ${dataset}
      maha_kwargs:
        kernel: local-full-g
        low_threshold: 0.9
        high_threshold: 0.99
        max_structures: 128
      ensemble_kwargs:
        uncertainty_keys:
        - force_sd
        - energy_sd
  - _target_: curator.simulate.callbacks.early_stop.EarlyStop
  _target_: curator.simulate.core.simulator.Simulator
  init_traj: ../test/LiFePO4.traj
  start_index: null
  run_kwargs:
    steps: 2
cfg: null
seed: 1234
run_path: ./runs/ensemble_uncertainty
model_path:
- ../example/train/ensemble/model_1
- ../example/train/ensemble/model_2
- ../example/train/ensemble/model_3
dataset: ../test/torchsim_uncertainty/dataset_small.traj
device: cpu
deploy: null
calculator: ${model_path}
