_target_: curator.simulate.callbacks.plumed_bias.PlumedBias
plumed:
  _target_: curator.interface.plumed.Plumed
  plumed_kwargs:
    input_file: ""
    input_lines: []
    timestep: 1.0
    kT: 1.0
    log: ""
    restart: false
  use_charge: false
  update_charge: false
  debug: false
  debug_interval: 1
apply_to_neb_images: false
