_target_: curator.simulate.callbacks.thermo.MDThermoLogger   # basic thermodynamic logger
variables: basic_energies                                   # variables to record
interval: 10                                                # logging interval in steps
header: true                                                # print header row
