[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "curator-torch"
version = "1.1.2"
description = "Library for implementation of message passing neural networks in Pytorch"
readme = "README.md"
authors = [
    { name = "xinyang", email = "xinyang@dtu.dk" },
]
license = { text = "MIT License" }
urls = { Homepage = "https://github.com/dtu-energy/curator.git" }
requires-python = ">=3.7"
dependencies = [
    "torch>=1.10",
    "ase",
    "e3nn==0.4.4",
    "torch-ema>=0.3.0",
    "toml",
    "numpy",
    "hydra-core>=1.2",
    "wandb",
    "lightning",
]

[project.optional-dependencies]
torch-scatter = ["torch-scatter"]
myqueue = ["myqueue"]
neighbor_list = ["asap3", "matscipy"]
all = ["myqueue", "torch-scatter", "asap3", "matscipy"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["curator", "curator.*"]