[metadata]
name = curator-torch
version = 1.2.0
description = Library for implementation of message passing neural networks in Pytorch
long_description = file: README.md
long_description_content_type = text/markdown
author = xinyang
author_email = xinyang@dtu.dk
license = MIT License
url = https://github.com/Yangxinsix/curator.git
project_urls =
    Source = https://github.com/Yangxinsix/curator
    Issues = https://github.com/Yangxinsix/curator/issues

[options]
packages = find:
python_requires = >=3.8
include_package_data = True
install_requires =
    torch>=1.9
    ase
    e3nn==0.4.4
    argcomplete
    torch-ema>=0.3.0
    toml
    numpy
    hydra-core>=1.2
    wandb
    lightning
    myqueue
    apsw

[options.packages.find]
include =
    curator
    curator.*
    curator_mcp
    curator_mcp.*

[options.extras_require] 
opt =
    torch-scatter
    asap3
    matscipy
mcp =
    mcp
torchsim =
    torch-sim-atomistic
all =
    myqueue
    mcp
    torch-scatter
    asap3
    matscipy
    torch-sim-atomistic
    cuequivariance-torch>=0.2.0
    cuequivariance-ops-torch-cu12>=0.2.0
cueq =
    cuequivariance-torch>=0.2.0
    cuequivariance-ops-torch-cu12>=0.2.0
foundation-nequip =
    nequip; python_version >= "3.10"
    matscipy
foundation-allegro =
    nequip-allegro; python_version >= "3.10"
    matscipy

[options.entry_points]
console_scripts =
    curator-train = curator.commands.hydra_entrypoints:train
    curator-tmptrain = curator.commands.hydra_entrypoints:tmptrain
    curator-simulate = curator.commands.hydra_entrypoints:simulate
    curator-evaluate = curator.commands.evaluate:evaluate_main
    curator-select = curator.commands.hydra_entrypoints:select
    curator-label = curator.commands.hydra_entrypoints:label
    curator-deploy = curator.commands.deploy:deploy_main
    curator-workflow = curator.workflow:workflow
    curator-convert = curator.commands.convert:convert_main
    curator-mcp = curator_mcp.server:main
    curator-backend-runner = curator_mcp.backend_runner:main
