[metadata]
name = curator-torch
version = 1.2.0
description = Library for implementation of message passing neural networks in Pytorch
long_description = file: README.md
long_description_content_type = text/markdown
author = xinyang
author_email = xinyang@dtu.dk
license = MIT License
url = https://github.com/Yangxinsix/curator.git
project_urls =
    Source = https://github.com/Yangxinsix/curator
    Issues = https://github.com/Yangxinsix/curator/issues

[options]
packages = find:
python_requires = >=3.8
include_package_data = True
install_requires =
    torch>=1.9
    ase
    e3nn==0.4.4
    argcomplete
    torch-ema>=0.3.0
    toml
    numpy
    hydra-core>=1.2
    wandb
    lightning
    myqueue
    aspw

[options.packages.find]
include =
    curator
    curator.*

[options.extras_require] 
opt =
    torch-scatter
    asap3
    matscipy
torchsim =
    torch-sim-atomistic
all =
    myqueue
    torch-scatter
    asap3
    matscipy
    torch-sim-atomistic
    cuequivariance-torch>=0.2.0
    cuequivariance-ops-torch-cu12>=0.2.0
cueq =
    cuequivariance-torch>=0.2.0
    cuequivariance-ops-torch-cu12>=0.2.0

[options.entry_points]
console_scripts =
    curator-train = curator.commands.train:train
    curator-tmptrain = curator.commands.train:tmptrain
    curator-simulate = curator.commands.simulate:simulate
    curator-evaluate = curator.commands.evaluate:evaluate_main
    curator-select = curator.commands.select:select
    curator-label = curator.commands.label:label
    curator-deploy = curator.commands.deploy:deploy_main
    curator-workflow = curator.workflow:workflow
    curator-convert = curator.commands.convert:convert_main
