model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${run_path}/model_path
  save_top_k: 1
  monitor: val_total_loss
  filename: best_model_{epoch}_{step}_{val_total_loss:.2f}
early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: val_total_loss
  min_delta: 0.0
  patience: ${task.patience}
  mode: min
learning_rate_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: epoch
ema:
  _target_: curator.train.ExponentialMovingAverage
  decay: 0.995
  use_num_updates: true
# batch_size_finder:
#   _target_: pytorch_lightning.callbacks.BatchSizeFinder
#   mode: binsearch
#   steps_per_trial: 5
