_target_: pytorch_lightning.callbacks.ModelCheckpoint   # saves checkpoints during training
dirpath: ${run_path}/model_path                        # directory to store checkpoints
save_top_k: 1                                          # keep best K checkpoints
monitor: val_total_loss                                # metric to monitor for ranking
filename: best_model_{epoch}_{step}_{val_total_loss:.2f}  # checkpoint filename template
