defaults:
  - optimizer: adam
  - scheduler: reduce_on_plateau
  - outputs: energy_force

_target_: curator.model.LitNNP
scheduler_monitor: val_total_loss
warmup_steps: 0
save_entire_model: True
load_entire_model: False
load_weights_only: True
init_new_domains_from: null
domain_mode: null
new_domains: null

# customize loss ratios
energy_weight: 1
forces_weight: 100
# per-atom energy loss (divide energy targets by n_atoms in loss only)
energy_per_atom_loss: true
# stress_weight: 50
patience: 200
