defaults:
  - optimizer: adam
  - scheduler: exponential

_target_: curator.model.LitNNP
scheduler_monitor: null
use_ema: False                         # exponential moving average
ema_decay: null
warmup_steps: 0

outputs:
  - _target_: curator.model.ModelOutput
    name: energy
    loss_fn:
      _target_: torch.nn.MSELoss
    loss_weight: ${energy_weight}
    metrics:
      mae:
        _target_: torchmetrics.regression.MeanAbsoluteError
      rmse:
        _target_: torchmetrics.regression.MeanSquaredError
        squared: false
  - _target_: curator.model.ModelOutput
    name: forces
    loss_fn:
      _target_: torch.nn.MSELoss
    loss_weight: ${forces_weight}
    metrics:
      mae:
        _target_: torchmetrics.regression.MeanAbsoluteError
      rmse:
        _target_: torchmetrics.regression.MeanSquaredError
        squared: false