_target_: ase.md.Andersen                               # Andersen thermostat integrator
_partial_: True                                         # allow hydra partial instantiation
timestep: ${multiply_fs: ${simulator.timestep}}         # timestep converted from fs
temperature_K: ${simulator.temperature}                 # target temperature in Kelvin
andersen_prob: 0.002                                    # collision probability
