_target_: ase.md.Langevin                                # Langevin thermostat integrator
_partial_: True                                          # allow hydra partial instantiation
timestep: "${multiply_fs: ${simulator.timestep}}"        # timestep converted from fs
temperature_K: ${simulator.temperature}                  # target temperature in Kelvin
friction: "${divide_by_fs: 0.01}"                        # friction constant converted from 1/fs
