_target_: ase.md.VelocityVerlet                         # Velocity Verlet integrator
_partial_: True                                         # allow hydra partial instantiation
timestep: ${multiply_fs: ${simulator.timestep}}         # timestep converted from fs
