_convert_: all
cfg: null
seed: 123
run_path: .
model_path: null
device: cuda
train_set: null
pool_set: null
data_url: null
data_batch_size: 8
select_batch_size: 100
method: lcmd_greedy
selection_feature: fg-sketch
target_layer: readout_mlp
save_features: null
save_selected_features: null
export_normalized_features: true
save_images: false
compute_features_only: false
target_domain: null
transforms: []

feature_specs:
  - preset: fg-sketch
    seed: ${seed}

  - preset: fg-sketch-rms
    seed: ${seed}

  - preset: fg-rff
    seed: ${seed}

  - preset: fg-sketch
    name: fg-sketch-sum-control
    layer_combine: sum
    seed: ${seed}
