_target_: curator.simulate.engines.ase_md.MDEngine   # wrapper around ASE MD engines
dynamics_cls: ase.md.langevin.Langevin                # ASE integrator class to use
timestep: 0.5                                         # MD timestep in femtoseconds
friction: 0.2                                         # Langevin friction coefficient
temperature_K: 300                                    # target temperature in Kelvin
