_target_: gpaw.GPAW
xc: PBE
mode: 
  name: pw
  ecut: 520
eigensolver: 
  name: dav
  niter: 1
occupations: 
  name: fermi-dirac 
  width: 0.05
  fixmagmom: true
maxiter: 200
kpts: [3,2,2]
  
  #mode.name: pw
  #mode.ecut: 520
  #eigensolver.name: dav
  #eigensolver.niter: 1
  #occupations.name: fermi-dirac
  #occupations.width: 0.05
  #occupations.fixmagmom: true
  #convergence.energy: 1e-05
  #convergence.density: 1
  #convergence.eigenstates: 1
