defaults:
  - calculator: default_calculator
  - logger: md_logger
  - dynamics: langevin
  - uncertainty: mahalanobis

_target_: curator.simulate.simulator.MDSimulator
init_traj: null                        # must be specified
out_traj: ${run_path}/MD.traj
start_index: -1
print_step: 1
dump_step: 100
max_steps: 1000
initialize_velocities: true
temperature: 298.15
variables:
  - step
  - temp
  - epot
  - ekin
  - etot
monitor: mahalanobis_distance