defaults:
  - engine: torchsim
  - /simulator/callbacks@callbacks.calc: calc_assign
  - /simulator/callbacks@callbacks.traj: trajectory_writer
  - /simulator/callbacks@callbacks.thermo: torchsim_logger
  - /simulator/callbacks@callbacks.stop: early_stop
  - _self_

_target_: curator.simulate.core.simulator.Simulator
init_traj: null
start_index: null
run_kwargs:
  steps: 100
