_target_: curator.simulate.uncertainty.EnsembleUncertainty   # ensemble-based uncertainty estimator
uncertainty_keys:
  - force_sd                                                 # standard deviation of forces
  - energy_sd                                                # standard deviation of energy
