simulator:
  calculator:
    _target_: curator.simulate.calculator.MLCalculator
    _partial_: true
    transforms: []
    energy_scale: 1.0
    forces_scale: 1.0
    model: ./example/train/model_path
  logger:
    _target_: curator.simulate.logger.MDLogger
    variables: full_thermodynamics
    interval: 1
    header: true
    monitor: mahalanobis_distance
    low: 0.05
    high: 0.5
    save_path: ./warning_struct.traj
    uncertain_count: null
  dynamics:
    _target_: ase.md.Langevin
    _partial_: true
    timestep: 0.5
    temperature_K: 298.15
    friction: 0.1
  uncertainty:
    _target_: curator.simulate.uncertainty.MahalanobisUncertainty
    high_threshold: 0.99
    low_threshold: 0.9
    dataset: ./example/LiFePO4.traj
    max_structures: 64
  _target_: curator.simulate.simulator.MDSimulator
  init_traj: ../LiFePO4.traj
  out_traj: ./MD.traj
  start_index: -1
  print_step: 1
  dump_step: 10
  max_steps: 50
  initialize_velocities: true
  temperature: 298.15
  variables:
  - step
  - temp
  - epot
  - ekin
  - etot
  - natoms
  monitor: mahalanobis_distance
cfg: config.yaml
seed: 1234
run_path: .
model_path: ../train/model_path
device: cpu
deploy: null
