simulator:
  _target_: curator.simulate.simulator.MDSimulator
  init_traj: ./example/LiFePO4.traj
  out_traj: ./MD.traj
  start_index: -1
  print_step: 1
  dump_step: 10
  max_steps: 50
  initialize_velocities: true
  temperature: 298.15
  variables:
    - step
    - temp
    - epot
    - ekin
    - etot
    - natoms
  monitor: mahalanobis_distance
  calculator:
    _target_: curator.simulate.calculator.MLCalculator
    model: ${model_path}
  dynamics:
    _target_: ase.md.Langevin
    _partial_: true
    timestep: 0.5
    temperature_K: ${simulator.temperature}
    friction: 0.1
  logger:
    _target_: curator.simulate.logger.MDLogger
    header: true
  uncertainty:
    _target_: curator.simulate.uncertainty.MahalanobisUncertainty
    dataset: ./example/LiFePO4.traj
    max_structures: 64

cfg: null
seed: 1234
run_path: .
model_path: ./example/train/model_path
device: cpu
deploy: null
