defaults:
  - model/representation: nequip
  - task/optimizer: adam_amsgrad
  - task/scheduler: reduce_on_plateau

seed: 123
run_path: .
energy_weight: 1
forces_weight: 1
patience: 200


data:
  datapath: /home/xinyang/aspirin_dft.traj
  cutoff: 4.0
  batch_size: 2
  num_train: 100
  num_val: 50
  train_val_split: sequential
  shuffle: false
  avg_num_neighbors: auto
  atomic_energies: null
  normalization: True
  atomwise_normalization: False
  scale_forces: True
  species:
    - C
    - H
    - O
  transforms:
    - _target_: curator.data.TypeMapper
      species: ${data.species}
    - _target_: curator.data.Asap3NeighborList
      cutoff: ${data.cutoff}

task:
  scheduler_monitor: val_total_loss
  optimizer:
    lr: 0.005
    weight_decay: 0.0
  scheduler:
    factor: 0.8
  # use_ema: true
  # ema_decay: 0.995


model:
  representation:
    num_elements: 3
    num_interactions: 4
    num_features: 32
    num_basis: 8
    power: 6
    lmax: 2
    parity: True
    resnet: False
    nonlinearity_type: gate
    nonlinearity_scalars:
      e: silu
      o: tanh
    nonlinearity_gates:
      e: silu
      o: tanh
    convolution_kwargs:
      invariant_layers: 2
      invariant_neurons: 64
      use_sc: True
  input_modules:
    - _target_: curator.layer.PairwiseDistance
      compute_neighborlist: False
      compute_distance_from_R: True
  output_modules:
    - _target_: curator.layer.AtomwiseReduce
    - _target_: curator.layer.GradientOutput
      grad_on_edge_diff: False
      grad_on_positions: True
    - _target_: curator.layer.GlobalRescaleShift
  
trainer:
  log_every_n_steps: 1
  logger:
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: ./logs
    name: curator-train