defaults:
  - model/representation: painn

data:
  datapath: /home/xinyang/aspirin_dft.traj
  num_train: 100
  num_val: 50
  species:
    - C
    - H
    - O

trainer:
  log_every_n_steps: 1
  logger:
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: ./logs
    name: curator-train