defaults:
  - model/representation: mace
  - task/optimizer: adam_amsgrad
  - task/scheduler: reduce_on_plateau

run_path: .

data:
  datapath: /home/xinyang/aspirin_dft.traj
  cutoff: 4.0
  batch_size: 5
  num_train: 1000
  num_val: 1000
  atomic_energies: null
  atomwise_normalization: False
  scale_forces: True
  species:
    - C
    - H
    - O
  transforms:
    - _target_: curator.data.TypeMapper
      species: ${data.species}
    - _target_: curator.data.Asap3NeighborList
      cutoff: ${data.cutoff}
      # return_cell_displacements: True

task:
  scheduler_monitor: val_total_loss
  use_ema: True                         # exponential moving average
  ema_decay: 0.99
  optimizer:
    lr: 0.01
  scheduler:
    factor: 0.8

trainer:
  logger:
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: ./logs
    name: curator-train

model:
  representation:
    num_interactions: 3
    # num_features: 128
    hidden_irreps: 128x0e + 128x1o

# model:
#   representation:
#     num_interactions: 3
#     num_features: 64
#     correlation: 3
#     lmax: 3
#     parity: True
#     num_basis: 8
#     power: 6
#     hidden_irreps: null
#     MLP_irreps: null
  input_modules:
    - _target_: curator.layer.PairwiseDistance
#      compute_neighborlist: False
#      compute_distance_from_R: True
  output_modules:
    - _target_: curator.layer.AtomwiseReduce
    - _target_: curator.layer.GradientOutput
      grad_on_edge_diff: True
      grad_on_positions: False
    - _target_: curator.layer.GlobalRescaleShift

# model:
#   representation:
#     num_elements: 3
#     num_interactions: 5
#     num_features: 64
#     num_basis: 8
#     power: 6
#     lmax: 3
#     parity: True
#     resnet: False
#     nonlinearity_type: gate
#     nonlinearity_scalars:
#       e: silu
#       o: tanh
#     nonlinearity_gates:
#       e: silu
#       o: tanh
#     convolution_kwargs:
#       invariant_layers: 2
#       invariant_neurons: 64
#       use_sc: True
#   input_modules:
#     - _target_: curator.layer.PairwiseDistance
#       compute_neighborlist: False
#       compute_distance_from_R: True
#   output_modules:
#     # - _target_: curator.layer.PerSpeciesRescaleShift
#     #   shifts:
#     #     C: -694.8563
#     #     H: -694.8563
#     #     O: -694.8563
#     - _target_: curator.layer.AtomwiseReduce
#     - _target_: curator.layer.GradientOutput
#       grad_on_edge_diff: False
#       grad_on_positions: True
#     - _target_: curator.layer.GlobalRescaleShift
#       # scale: 27.8740